### ISSUE TITLE
Hey :wave:

### ISSUE THREAD

**Issue by joanofdart** [emanuel-braz/one_context#5]
Great package! : )
Just wondering about nested navigators. Do you have an example for this matter? 🤔

**Comment by emanuel-braz** [comment]
Hi @joanofdart, thanks for the question! The quick answer is, in order to keep the package as lightweight as possible, OneContext does not intend to deal with nested navigators. Since navigation nested with many global keys can end up impacting the performance of the application.

In practice, OneContext creates a Navigator just below the MaterialApp, and exposes it to you globally. But still, if necessary, you can create new Navigators and use them in the way that suits your need. Even with or without the need for context. Yep, it's native for Flutter :)

For this reason, think of OneContext().navigator as your root navigator, and use navigator nests, as needed by your application.

From the Flutter docs:
> ... there must exist a "root" [Navigator] that sits above the tab navigation. As a result, each of the tab's [Navigator] s are actually nested [Navigator] s sitting below a single root [Navigator].

A great post on that subject, with examples, is https://medium.com/coding-with-flutter/flutter-case-study-multiple-navigators-with-bottomnavigationbar-90eb6caa6dbf
