### ISSUE TITLE
Can we control the runApp function in OnePlatform when needed?

### ISSUE THREAD

**Issue by bitores** [emanuel-braz/one_context#6]
```dart

static Widget _app;
static set app(OnePlatformBuilder builder) => reboot(builder: builder);

 static void reboot({OnePlatformBuilder builder, VoidCallback setUp}) {
    setUp?.call();
    // ignore: unused_local_variable
    Widget oldWidget = _app;
    Future.delayed(Duration.zero, () {
      Widget newWidget = builder?.call();
      runApp(_app = newWidget ??
          OneBasicWidget(
            key: UniqueKey(),
            child: _app,
          ));
      oldWidget = null;
    });
  }
```

**Comment by emanuel-braz** [comment]
@bitores you can call `OnePlatform.reboot` when you need, but be awareness it's experimental yet.

When you call `OnePlatform.reboot`, it will call runApp under the hood and it will detach the root widget from the screen and attach it again. If you pass a new widget, the previous widget will be detached from the root and the new one will be placed instead. 

The new widget tree is compared against the previous widget tree and any differences are applied to the underlying render tree, similar to what happens when a StatefulWidget rebuilds after calling `State.setState`

e.g.
```dart
OnePlatform.reboot(
    setUp: () { // Use this function to implement some app logic before attaching the new widget
        OneContext().key = GlobalKey<NavigatorState>();
    },
    builder: () => MyApp(),
);
```
